---
name: Update Gemfile
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - name: Run bundle update
        run: bundle update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump Gemfile
          branch: bump/update-gemfile
          title: 'Update Gemfile'




