---
name: Update Gemfile
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  bundle-update:
    name: bundle update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
        run: bundle update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: bump/update-gemfile
          title: Update Gemfile
