---
name: Update Gemfile
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  bundle-update:
    name: bundle update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3

      - name: Run bundle update
        run: bundle update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Bump Gemfile
          branch: bump/update-gemfile
          title: 'Update Gemfile'




