---
name: Update Gemfile
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  bundle-update:
    name: bundle update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install libicu-dev
        run: apt install libicu-dev

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Pull request on bundle update
        uses: supermanner/pull-request-on-bundle-update@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_user_name: MoretS
          git_email: smoret1997@gmail.com
          bundler_version: 2.1.4
